### ISSUE TITLE
Using inheritance with mutations and queries

### ISSUE THREAD

**Issue by jwoertink** [graphql-crystal/graphql#11]
I wanted to break out my mutations and queries to avoid them being a dumping ground like they are now, but when I try to use some inheritance, I get compilation errors. Maybe I'm just missing something though?

I want to turn this code:

```crystal
@[GraphQL::Object]
class Mutation
  include GraphQL::ObjectType
  include GraphQL::MutationType

  @[GraphQL::Field]
  def echo(str : String) : String
    str
  end

  @[GraphQL::Field]
  def count(num : Int32) : Int32
    num
  end
end

schema = GraphQL::Schema.new(Query.new, Mutation.new)
```

Into something more like this:

```crystal
@[GraphQL::Object]
class BaseMutation
  include GraphQL::ObjectType
  include GraphQL::MutationType
end

class EchoMutation < BaseMutation
  @[GraphQL::Field]
  def echo(str : String) : String
    str
  end
end

class CountMutation < BaseMutation
  @[GraphQL::Field]
  def count(num : Int32) : Int32
    num
  end
end

schema = GraphQL::Schema.new(Query.new, BaseMutation.new)
```

The first downside here is that I can't make `BaseMutation` abstract since I have to send an instance to the `Schema`. But that aside, when I try something like this, I get this error:

```
There was a problem expanding macro 'included'

Code in macro 'inherited'

 3 | include GraphQL::ObjectType
     ^
Called macro defined in lib/graphql/src/graphql/object_type.cr:2:3

 2 | macro included

Which expanded to:

 > 3 | # :nodoc:
 > 4 | def _graphql_type : String
 > 5 |   {{ (@type.annotation(::GraphQL::Object))["name"] || (@type.name.split("::")).last }}
                                                 ^
Error: undefined macro method 'NilLiteral#[]'
```

**Comment by jwoertink** [comment]
I do have the `::Object` annotation on the parent class. My ultimate goal here is to make this shard easier to use within Lucky. Right now it requires a ton of boilerplate, and SOOOO many annotations 😂 I'm trying to find a way to reduce that noise, and include some generation code. My thought was that the top-level class would be hidden behind the shard, and do all the include stuff you'd need.

Turning the sub-classes in to modules, and then including them would probably work to clean up my app a bit, but I don't think it would work for my Lucky integration. Thanks for the suggestion though! I'll see if I can think about this in another way 😄

**Comment by jgillich** [comment]
The includes are unfortunately required for the macros to work. Although we could possibly turn them into superclasses? I'm not sure if I ever tried that.

And the annotations..hm, the idea was to make it explicit which fields are part of the API because otherwise you'd have to explicitly note which one's aren't ([what juniper does](https://graphql-rust.github.io/juniper/current/types/objects/defining_objects.html#skipping-fields)). All fields should have descriptions anyway which are set via the annotation. Compared to most other GraphQL implementations, the amount of boilerplate required here is actually quite small. :smile:

But if you have ideas to make integration with lucky easier, let me know.

**Comment by jwoertink** [comment]
I have to admit, I'm working on my very first GraphQL app, so I have literally no other experience to compare to 😅 . It might just be that I don't understand GraphQL well enough to really grasp the patterns.

One of the patterns we use in almost every one of our mutation methods is this:

```crystal
def some_mutation_method(context : Graph::Context, arg1 : String, arg2 : String.....) : MutationOutcome
  outcome = MutationOutcome.new(success: false)
  if user = context.current_user
    # all the logic
  end

  outcome
end
```

I'll have to keep playing around to see if there's a different way I can abstract out some of these patterns to help clean up our code.
