### ISSUE TITLE
Issues using Int64 in input objects

### ISSUE THREAD

**Issue by jwoertink** [graphql-crystal/graphql#19]
Any time I try to use `Int64` in an input object, I get this error:

```
Which expanded to:

 > 34 |                 
 > 35 |                 when Int
 > 36 |                   arg_value.as(Int64)
                          ^
Error: can't cast Int32 to Int64
```

It works fine with `Int32` though.

```crystal
@[GraphQL::InputObject]
class MenuItemInput
  include GraphQL::InputObjectType

  @title : String
  @amount : Int64

  @[GraphQL::Field]
  def initialize(@title : String, @amount : Int64)
  end

  @[GraphQL::Field]
  def title : String
    @title
  end

  @[GraphQL::Field]
  def amount : Int64
    @amount
  end
end
```

**Comment by jgillich** [comment]
Int is 32bit in GraphQL, see https://spec.graphql.org/June2018/#sec-Int

Allowing them on fields is actually a mistake

**Comment by jwoertink** [comment]
I noticed that `Int64` is usable on output objects. Like if a mutation returns a serialized object, and that object has a Graph Field that returns `Int64`, it's ok. Should that be throwing an error too?

Also, when I started looking at how other libraries handle this, it looks like it's sort of mixed. Like [Rust](https://docs.rs/graphql-int64-scalar/latest/graphql_int64_scalar/) seems to have some Int64 for scalar, but [Go](https://github.com/graphql-go/graphql/issues/257) seems to be more on "do it yourself" level. Then the [Ruby](https://graphql-ruby.org/api-doc/1.13.6/GraphQL/Types/BigInt.html) just adds it right in. My guess is since it's not native to the spec, you'd have to add in a package like https://www.npmjs.com/package/graphql-bigint in order for it to work on the front-end... 

Maybe this could also just support it with a note that you'll have to handle bigints on the front on your own?

**Comment by jgillich** [comment]
Yea, the current Int64 support on fields should be removed. I'll try to make a shard with some additional int scalars soon, have been wanting to verify the usefulness of the current custom scalar implementation anyhow

**Comment by jwoertink** [comment]
Sweet! I think a secondary shard makes sense. That would allow this one to stay close to spec, and still give additional functionality.

**Comment by jgillich** [comment]
`GraphQL::Scalars::BigInt` is now available, example:
```crystal
@[GraphQL::Field]
def add(bi : GraphQL::Scalars::BigInt, i : Int32) : GraphQL::Scalars::BigInt
  GraphQL::Scalars::BigInt.new(bi.value + i)
end
```

**Comment by jwoertink** [comment]
Awesome!
