### ISSUE TITLE
Using array enum as argument requires `Array(NoReturn)`

### ISSUE THREAD

**Issue by grantspeelman** [graphql-crystal/graphql#2]
Thanks for the shard, it's been really nice playing with it.

i want to take a Array of Enums as a argument but it also requires me adding overload method with Array(NoReturn).

```crystal
  module Enums
    @[GraphQL::Enum(description: "Source on where to get person data")]
    enum Source
      TEST
      FAKER
    end
  end

  @[GraphQL::Field]
  def person(email : String, sources : Array(Enums::Source)) : Person
    Person.new.tap do |p|
      p.email = email
    end
  end

  def person(email : String, sources : Array(NoReturn)) : Person
    raise "Should never happen"
  end
```

Is it possible to update to not have to do `Array(NoReturn)` method?

**Comment by jgillich** [comment]
If this is the issue I'm thinking of then I've already started working on a fix a while ago, will try to finish it soon.

**Comment by grantspeelman** [comment]
Seems it does not like it as a variable and give the error: `wrong type for argument sources` 
![Screenshot_20201120_105713](https://user-images.githubusercontent.com/98919/99738754-57166c80-2b1f-11eb-8d1a-72ed061d0a8e.png)

if i change the input type to an array of strings, it's happy with that.
![Screenshot_20201120_105620](https://user-images.githubusercontent.com/98919/99738802-70b7b400-2b1f-11eb-8c4b-e1bde01d2fb6.png)
