### ISSUE TITLE
Exceptions are being swallowed by GraphQL

### ISSUE THREAD

**Issue by jwoertink** [graphql-crystal/graphql#20]
I'm not sure if this is just something I have configured wrong... .but it seems that any Crystal level exception is actually being swallowed up by GraphQL and then rendered on the front end. So I actually see them in my JS console. Is there a way to not do that?

Right now I have 2 instances of [Bugsnag](https://bugsnag.com/) on my app. One on the backend for Lucky, and then one on the frontend for Vue. Exceptions that happen from Lucky are reported in Vue because they seem to just be blanket rescued and passed up the stack. 

Here's an example of my graph call.

```crystal
class Api::Graphql::Index < ApiAction
  param query : String

  post "/api/graphql" do
    raw_json(
      schema.execute(query, variables, operation_name, Graph::Context.new(current_user?)),
    )
  end

  private def schema
    GraphQL::Schema.new(Graph::Queries.new, Graph::Mutations.new)
  end

  private def operation_name
    params.from_json["operationName"].as_s
  end

  private def variables
    params.from_json["variables"].as_h
  end
end
```

The exception could happen in the `current_user?` method, or within the `Graph::Queries` or `Graph::Mutations` that I have

**Comment by jgillich** [comment]
Exceptions are caught and added to errors by design https://github.com/graphql-crystal/graphql/blob/8c6dc73c0c898ca511d9d12efefca7c837c25946/src/graphql/object_type.cr#L46

This is similar to how Juniper and graphql-js work, although I'm not opposed to making this behavior configurable.

**Comment by jwoertink** [comment]
That would be great! Lucky allows us to configure which errors get reported (e.g. someone tampering with the site, etc... could be ignored). We can also better control what the response is back to the client.

**Comment by jgillich** [comment]
#24 open for feedback. Still need to add some custom exception types to make it easier to tell them apart
