### ISSUE TITLE
ObjectType inheritance issues

### ISSUE THREAD

**Issue by watzon** [graphql-crystal/graphql#45]
I'm attempting to do codegen for frontend code using graphql introspection, but having some issues. The root of my problems seem to be that `GraphQL::Field` annotations aren't inherited by extending types.

This means that if I have a `PaginatedOutcome` class containing `total_count`, `total_pages`, and `has_more` fields and then I attempt to extend that object with `UsersPaginatedOutcome` which adds the `users` field, all that is seen by introspection is the `users` field which breaks codegen. It also makes it so that utilities like Postman don't work in these cases because they rely on introspection to make sure the fields are correct.

**Comment by jgillich** [comment]
> annotations aren't inherited by extending types

Are you sure? Do you have a code sample?

**Comment by watzon** [comment]
Basically I have this:

```crystal
module Graph::Objects
  @[GraphQL::Object]
  class PaginatedOutcome
    include GraphQL::ObjectType

    getter scope, page, limit

    def initialize(@scope : T, @page : Int32, @limit : Int32) forall T
    end

    @__total_count : Int64? = nil

    @[GraphQL::Field]
    def total_count : GraphQL::Int64Scalar
      value = if @__total_count.nil?
                @__total_count = scope.reset_limit.reset_offset.select_count
              else
                @__total_count.as(Int64)
              end

      GraphQL::Int64Scalar.new(value)
    end

    @[GraphQL::Field]
    def total_pages : GraphQL::Int64Scalar
      value = (total_count.value / limit).ceil.to_i64
      GraphQL::Int64Scalar.new(value)
    end

    @[GraphQL::Field]
    def has_more : Bool
      total_count.value > (offset + limit)
    end

    private def offset
      (page - 1) * limit
    end
  end
end
```

and this

```crystal
module Graph::Objects
  @[GraphQL::Object]
  class OfficeUsersPaginatedOutcome < Graph::Objects::PaginatedOutcome
    include GraphQL::ObjectType

    property scope : UserQuery

    @[GraphQL::Field]
    def users : Array(OfficeUserSerializer)
      OfficeUserSerializer.for_collection(
        scope.limit(limit).offset(offset)
      )
    end
  end
end
```

but the generated schema contains the following `OfficeUsersPaginatedOutcome`:

```json
{
  "kind": "OBJECT",
  "name": "OfficeUsersPaginatedOutcome",
  "description": null,
  "fields": [
    {
      "name": "users",
      "description": null,
      "args": [],
      "type": {
        "kind": "NON_NULL",
        "name": null,
        "ofType": {
          "kind": "LIST",
          "name": null,
          "ofType": {
            "kind": "NON_NULL",
            "name": null,
            "ofType": {
              "kind": "OBJECT",
              "name": "OfficeUserSerializer",
              "ofType": null
            }
          }
        }
      },
      "isDeprecated": false,
      "deprecationReason": null
    }
  ],
  "inputFields": null,
  "interfaces": [],
  "enumValues": null,
  "possibleTypes": null
}
```

**Comment by jgillich** [comment]
Do the fields on `PaginatedOutcome` resolve? We probably need to iterate `.descendants` in the document macro like we do in the resolver

https://github.com/graphql-crystal/graphql/blob/30643003f84062d9c5f8ca23a0702078cee824e7/src/graphql/object_type.cr#L31

https://github.com/graphql-crystal/graphql/blob/30643003f84062d9c5f8ca23a0702078cee824e7/src/graphql/document.cr#L91

**Comment by watzon** [comment]
They seem to resolve in situations where introspection isn't being used. The current frontend isn't using introspection, and this query returns all of the necessary information.
